/*
 * Copyright Red Thread Labs LLC. All rights reserved.
 * Licensed under the BSD 2-Clause License.
 */

/**
 * The wire format for the `POST /logs` ingest endpoint: what a remote client
 * (browser, React Native) sends. Defined here so the client SDK, the server, and
 * the viewer all share one definition.
 *
 * The wire records ARE (modulo a few server-stamped fields) the on-disk records,
 * in the same units — timestamps are epoch MICROSECONDS, durations are
 * MILLISECONDS — so the ingest endpoint forwards them as-is rather than
 * unwrapping and re-wrapping each one. The server's only per-record job is to
 * stamp batch-level facts it owns (lifetime_id, context.user from the JWT, the
 * source IP) and write to the channel.
 */

/** This package's version: the value a writer puts in {@link RecordOrigin.schema}. */
export const SCHEMA_VERSION = '0.6.0';

export type JsonValue =
  | string
  | number
  | boolean
  | null
  | JsonValue[]
  | { [key: string]: JsonValue };

export type LogLevel = 'debug' | 'info' | 'warn' | 'error';

export interface RecordBatch {
  user_id?: string;
  /**
   * Id for this SDK lifetime (one app launch / process run), generated by the
   * SDK. The join key between records and the once-per-lifetime `metadata`
   * record that carries this launch's RecordOrigin.
   */
  lifetime_id?: string;
  /**
   * This lifetime's RecordOrigin (service + environment). Sent on the first
   * batch of a launch and again when it changes; the server writes it as an
   * in-stream `metadata` record keyed by `lifetime_id`.
   */
  origin?: RecordOrigin;
  events: EventRecord[];
  transactions: TransactionRecord[];
  spans: SpanRecord[];
}

/** Who a visitor is: a person, an agent (an SDK, a CLI, an MCP client), or the system itself. */
export type VisitorKind = 'human' | 'agent' | 'system';

export const VISITOR_KINDS: readonly VisitorKind[] = ['human', 'agent', 'system'];

/**
 * The surface a record came through: a browser page, a plain HTTP fetch, a
 * CLI, an MCP client, an agent thread, an edge (CDN) log line, or the server
 * acting on its own behalf.
 */
export type Via = 'browser' | 'fetch' | 'cli' | 'mcp' | 'thread' | 'edge' | 'server';

export const VIAS: readonly Via[] = ['browser', 'fetch', 'cli', 'mcp', 'thread', 'edge', 'server'];

/** The long-lived first-party identity behind a record: one per person (or agent), signed in or not. */
export interface VisitorContext {
  id: string;
  kind: VisitorKind;
}

/**
 * One visit: a client-generated id, carried explicitly (a new one after 30
 * minutes without an event, or on a new tab). `n` is the visitor's visit
 * ordinal, when known.
 */
export interface VisitContext {
  id: string;
  n?: number;
}

/** What acted, and through which surface. `agent` names the client software when there is one. */
export interface ActorContext {
  agent?: { name: string; version?: string };
  via: Via;
}

/** The page a record is about. `release` is the documentation release shown on the page, when it has one. */
export interface PageContext {
  url: string;
  path: string;
  title?: string;
  referrer?: string;
  release?: string;
}

/** The campaign (UTM) parameters of the visitor's first touch. */
export interface CampaignContext {
  source?: string;
  medium?: string;
  name?: string;
  term?: string;
  content?: string;
}

/** Location derived server-side from the source IP (the IP itself is not kept). */
export interface GeoContext {
  country?: string;
  region?: string;
  city?: string;
}

/**
 * Per-record context, shared by every record kind. `labels` is the arbitrary
 * key-value attribute bag; `user` is the identity the record is attributed to.
 * The analytics sub-objects (`visitor`, `visit`, `actor`, `page`, `campaign`,
 * `geo`, `entity`) are typed and optional; see docs/ANALYTICS_CONTEXT.md.
 * Readers ignore sub-objects they do not know.
 */
export interface RecordContext {
  /** Arbitrary key-value attributes. Flat; the place for anything not named below. */
  labels?: Record<string, JsonValue>;
  /** The user this record is attributed to. */
  user?: { id?: string };
  visitor?: VisitorContext;
  visit?: VisitContext;
  actor?: ActorContext;
  page?: PageContext;
  campaign?: CampaignContext;
  geo?: GeoContext;
  /**
   * The consumer's own things this record concerns, named by id or address,
   * e.g. `{ project: "proj_…", docs_page: "/reference/…" }`. One level,
   * strings only. The key vocabulary belongs to the consumer, not to tracelog.
   */
  entity?: Record<string, string>;
}

/**
 * A discrete log entry — something that happened at an instant: a log line or a
 * behavioral event, carrying a level, message, and context labels. Events are
 * NOT timed: a timed operation is a transaction/span, never an event with a
 * duration.
 */
export interface EventRecord {
  /** Event category, e.g. 'auth', 'billing', 'startup'. Default: 'client-log' */
  type: string;
  /** Epoch microseconds */
  timestamp: number;
  level: LogLevel;
  message: string;
  /** Serialized error info. `code` is the structured error code. */
  error?: { message: string; type?: string; code?: string; stack?: string };
  /** UI locale at record time, e.g. 'en-US'. Can change mid-launch, so per-event. */
  locale?: string;
  /** Labels + user (see RecordContext). */
  context?: RecordContext;
  /**
   * Minutes east of UTC at the moment the event was recorded (ISO-8601 sign:
   * `localWallClock = UTC + tz_offset`). Captured per-event because buffered
   * clients can record across DST or travel and flush later. e.g. EST = -300,
   * IST = +330.
   */
  tz_offset?: number;
}

/**
 * A root timed operation — the top of a trace (a request, a job, an agent run).
 * Recorded as a `transaction`. Child work hangs off it as {@link SpanRecord}s.
 */
export interface TransactionRecord {
  /** 16-char hex ID, generated client-side. Also the trace's root id. */
  id: string;
  /** 32-char hex trace ID, shared by the whole trace */
  trace_id: string;
  /** Operation name, e.g. 'parallel-search' */
  name: string;
  /** Transaction type, e.g. 'request', 'agent', 'app'. Default: 'app' */
  type: string;
  /** Start time, epoch microseconds */
  timestamp: number;
  /** Duration in milliseconds */
  duration: number;
  outcome: 'success' | 'failure' | 'unknown';
  /** Labels + user (see RecordContext). */
  context?: RecordContext;
  /** Minutes east of UTC at record time (see EventRecord.tz_offset). */
  tz_offset?: number;
}

/**
 * A timed sub-operation within a transaction — recorded as a `span`. Always has
 * a parent (its transaction, or another span) and belongs to one transaction.
 */
export interface SpanRecord {
  /** 16-char hex ID, generated client-side */
  id: string;
  /** 32-char hex trace ID, shared by the whole trace */
  trace_id: string;
  /** ID of the transaction (trace root) this span belongs to */
  transaction_id: string;
  /** 16-char hex ID of the immediate parent (the transaction or another span) */
  parent_id: string;
  /** Operation name, e.g. 'search:hanzi' */
  name: string;
  /** Span type, e.g. 'db', 'external', 'app'. Default: 'app' */
  type: string;
  /** Start time, epoch microseconds */
  timestamp: number;
  /** Duration in milliseconds */
  duration: number;
  outcome: 'success' | 'failure' | 'unknown';
  /** Labels + user (see RecordContext). */
  context?: RecordContext;
  /** Minutes east of UTC at record time (see EventRecord.tz_offset). */
  tz_offset?: number;
}

/**
 * Describes who/what produced records — a service and its environment. Carried
 * by a `metadata` record in two scopes: the per-file header (the writer's
 * origin, file-scoped) and, for a client, in-stream once per launch keyed by
 * `lifetime_id`. Records don't carry the origin; they carry `lifetime_id` (or,
 * server-side, sit in the file) and join to it.
 *
 * `service` + `runtime` are the common core; `host` is server-flavored; `device`
 * is client-flavored. (locale/timezone are NOT here — they can change mid-launch,
 * so they live per-record: `EventRecord.locale` and `tz_offset`.)
 */
export interface RecordOrigin {
  /** The SDK lifetime (app launch / process run) this RecordOrigin describes. Join key. */
  lifetime_id?: string;
  /**
   * The tracelog-schema version the batch was written against, e.g. "0.6.0",
   * so a reader knows which fields to expect. A client sets it from
   * {@link SCHEMA_VERSION}.
   */
  schema?: string;
  /** Application / service name + version. */
  service: { name: string; version: string };
  /** Runtime, e.g. 'react-native', 'node', 'browser'. */
  runtime: { name: string; version: string };
  os?: { name: string; version: string };
  /** Server-flavored: the host the service runs on. */
  host?: { name?: string };
  /** Client-flavored: the device the app runs on. */
  device?: {
    /**
     * Opaque, consumer-defined identifier for the device or installation — an
     * app's own id, a hardware id, whatever the consumer chooses. The framework
     * treats it as an opaque string and never interprets it. Stable across this
     * device's launches, so records join to it through the origin (lifetime_id).
     */
    id?: string;
    model?: string;
    brand?: string;
    type?: string;
    /** Device performance tier. */
    year_class?: number;
    screen?: { width: number; height: number; pixel_ratio: number };
  };
}
